# AuthZEN Discovery Configuration Example
# This example demonstrates how to configure the external URL for .well-known discovery

# Server configuration
server:
  host: "0.0.0.0"                          # Listen on all interfaces
  port: "6001"                              # Internal port
  external_url: "https://pdp.example.com"   # External URL for AuthZEN discovery
  frequency: 5m                             # Pipeline update frequency

# Logging configuration
logging:
  level: "info"
  format: "json"
  output: "stdout"

# Pipeline configuration
pipeline:
  timeout: 30s
  max_request_size: 10485760  # 10MB
  max_redirects: 3
  allowed_hosts: []

# Security configuration
security:
  rate_limit_rps: 100
  enable_cors: false
  allowed_origins: []

# Example: When deployed behind a reverse proxy (e.g., nginx, Caddy, AWS ALB)
# The external_url setting ensures that the .well-known/authzen-configuration
# endpoint returns the correct public-facing URL for PDP discovery.
#
# GET https://pdp.example.com/.well-known/authzen-configuration
# Returns:
# {
#   "policy_decision_point": "https://pdp.example.com",
#   "access_evaluation_endpoint": "https://pdp.example.com/evaluation"
# }
#
# This can also be configured via:
# 1. Command-line flag: --external-url https://pdp.example.com
# 2. Environment variable: GO_TRUST_EXTERNAL_URL=https://pdp.example.com
# 3. Config file: server.external_url (as shown above)
#
# Priority order: CLI flag > Environment variable > Config file > Default (http://host:port)
