basePath: /
definitions:
  api.HealthResponse:
    properties:
      status:
        type: string
      timestamp:
        type: string
    type: object
  api.ReadinessResponse:
    properties:
      last_processed:
        type: string
      message:
        type: string
      ready:
        type: boolean
      status:
        type: string
      timestamp:
        type: string
      tsl_count:
        type: integer
    type: object
  authzen.Action:
    description: Action (role) in an AuthZEN trust evaluation request
    properties:
      name:
        description: The role name
        example: http://ec.europa.eu/NS/wallet-provider
        type: string
    type: object
  authzen.EvaluationRequest:
    description: AuthZEN trust evaluation request (draft-johansson-authzen-trust)
    properties:
      action:
        allOf:
        - $ref: '#/definitions/authzen.Action'
        description: Optional role constraint
      context:
        additionalProperties:
          type: string
        description: Optional context (MUST NOT be critical)
        type: object
      resource:
        allOf:
        - $ref: '#/definitions/authzen.Resource'
        description: The public key to be validated
      subject:
        allOf:
        - $ref: '#/definitions/authzen.Subject'
        description: The name to be bound to the key
    type: object
  authzen.EvaluationResponse:
    description: AuthZEN evaluation response with trust decision
    properties:
      context:
        allOf:
        - $ref: '#/definitions/authzen.EvaluationResponseContext'
        description: Optional context with decision details
      decision:
        description: Whether the name-to-key binding is authorized
        example: true
        type: boolean
    type: object
  authzen.EvaluationResponseContext:
    description: Context information for evaluation response
    properties:
      id:
        description: Optional identifier for the decision
        example: decision-123
        type: string
      reason:
        description: Reason information (user or admin)
        type: object
    type: object
  authzen.Resource:
    description: Resource (public key) in an AuthZEN trust evaluation request
    properties:
      id:
        description: MUST match subject.id
        example: did:example:123
        type: string
      key:
        description: Public key data (JWK object or x5c array)
        items:
          type: string
        type: array
      type:
        description: MUST be "jwk" or "x5c"
        example: x5c
        type: string
    type: object
  authzen.Subject:
    description: Subject in an AuthZEN trust evaluation request
    properties:
      id:
        description: The name bound to the public key
        example: did:example:123
        type: string
      type:
        description: MUST be "key"
        example: key
        type: string
    type: object
host: localhost:6001
info:
  contact:
    email: noreply@sunet.se
    name: SUNET
    url: https://github.com/SUNET/go-trust
  description: |-
    Trust decision engine for ETSI TS 119612 Trust Status Lists (TSLs)

    Go-Trust provides AuthZEN-based trust decisions for X.509 certificates using ETSI trust status lists.
    It processes TSLs, validates certificates, and provides health/metrics endpoints for production deployment.
  license:
    name: BSD-2-Clause
    url: https://opensource.org/licenses/BSD-2-Clause
  termsOfService: https://github.com/SUNET/go-trust
  title: Go-Trust API
  version: "1.0"
paths:
  /evaluation:
    post:
      consumes:
      - application/json
      description: |-
        Evaluates whether a name-to-key binding is trusted according to loaded TSLs

        This endpoint implements the AuthZEN Trust Registry Profile as specified in
        draft-johansson-authzen-trust. It validates that a public key (in resource.key)
        is correctly bound to a name (in subject.id) according to ETSI TS 119612 Trust Status Lists.

        The request MUST have:
        - subject.type = "key" and subject.id = the name to validate
        - resource.type = "jwk" or "x5c" with resource.key containing the public key/certificates
        - resource.id MUST equal subject.id
        - action (optional) with name = the role being validated
      parameters:
      - description: AuthZEN Trust Registry Evaluation Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/authzen.EvaluationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Trust decision (decision=true for trusted, false for untrusted)
          schema:
            $ref: '#/definitions/authzen.EvaluationResponse'
        "400":
          description: Invalid request format or validation error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Evaluate trust decision (AuthZEN Trust Registry Profile)
      tags:
      - AuthZEN
  /health:
    get:
      description: Returns OK if the server is running and able to handle requests
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.HealthResponse'
      summary: Liveness check
      tags:
      - Health
  /healthz:
    get:
      description: Returns OK if the server is running and able to handle requests
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.HealthResponse'
      summary: Liveness check
      tags:
      - Health
  /info:
    get:
      description: |-
        Returns detailed summaries of all loaded Trust Status Lists

        This endpoint provides comprehensive information about each TSL including:
        - Territory code
        - Sequence number
        - Issue date
        - Next update date
        - Number of services
      produces:
      - application/json
      responses:
        "200":
          description: tsl_summaries
          schema:
            additionalProperties: true
            type: object
      summary: Get TSL information
      tags:
      - Status
  /readiness:
    get:
      description: Returns ready status if pipeline has been processed and TSLs are
        loaded
      produces:
      - application/json
      responses:
        "200":
          description: Service is ready
          schema:
            $ref: '#/definitions/api.ReadinessResponse'
        "503":
          description: Service is not ready
          schema:
            $ref: '#/definitions/api.ReadinessResponse'
      summary: Readiness check
      tags:
      - Health
  /ready:
    get:
      description: Returns ready status if pipeline has been processed and TSLs are
        loaded
      produces:
      - application/json
      responses:
        "200":
          description: Service is ready
          schema:
            $ref: '#/definitions/api.ReadinessResponse'
        "503":
          description: Service is not ready
          schema:
            $ref: '#/definitions/api.ReadinessResponse'
      summary: Readiness check
      tags:
      - Health
  /status:
    get:
      description: Returns the current server status including TSL count and last
        processing time
      produces:
      - application/json
      responses:
        "200":
          description: tsl_count, last_processed
          schema:
            additionalProperties: true
            type: object
      summary: Get server status
      tags:
      - Status
schemes:
- http
- https
swagger: "2.0"
tags:
- description: Health check and readiness endpoints for Kubernetes and monitoring
    systems
  name: Health
- description: Server status and TSL information endpoints
  name: Status
- description: AuthZEN protocol endpoints for trust decision evaluation
  name: AuthZEN
